dataSources:
    ds0: !!com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test0
        username: root
        password: monsterHan
    ds1: !!com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test1
        username: root
        password: monsterHan
shardingRule:
    tables:
        t_order:
            actualDataNodes: ds${0..1}.t_order{0..4}
            databaseStrategy:
                inline:
                    shardingColumn: user_id
                    algorithmExpression: ds${user_id % 2}
            tableStrategy:
                inline:
                    shardingColumn: order_id
                    algorithmExpression: t_order{order_id % 2}
            keyGeneratorColumnName: id
    bindingTables:
        - t_order
    defaultDataSourceName: ds0
    defaultDatabaseStrategy:
        inline:
            shardingColumn: id
            algorithmExpression: ds${id % 2}
    defaultTableStrategy:
        none:
    props:
        sql.show: true